### PR TITLE
Update seeds for RubyConf 2019

### PR DESCRIPTION
**Pull request by mileszs**
I've updated the seeds for RubyConf 2019, and run a quick local test. 

I also upgraded to Ruby 2.6.2. Everything seemed to work fine locally for me. I admittedly did this all pretty quick without super-thorough checking. I'm hoping the relatively small surface area of this app means I did enough. :-)

### CODE REVIEW

**Comment by mileszs** [comment]
@unixmonkey Anything I can do to get this going?

**Comment by unixmonkey** [comment]
This is good. Thank you. I’ll get it deployed shortly.

**Comment by unixmonkey** [comment]
This is now deployed and seeded.
BTW, I invited you to have commit access, and would be happy to invite you to Heroku if you like.
Are you using your personal address these days?

**Comment by mileszs** [comment]
@unixmonkey That'd be cool! miles@mileszs.com is best, yes.

**Comment by unixmonkey** [comment]
Invited!

**Pull request merged**
